kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    # add a mount from /tmp on the host to /data/db on the node
    extraMounts:
      - hostPath: /tmp
        containerPath: /data/db
